# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-07-14 14:41+0100\n"
"PO-Revision-Date: 2023-03-17 10:21+0100\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 3.2.2\n"

#: venv/lib/python3.10/site-packages/dj_rest_auth/app_settings.py:75
msgid ""
"The '{}' setting has been removed. Please refer to '{}' for available "
"settings."
msgstr ""
"Le paramètre '{}' a été supprimé. Veuillez vous référer à '{}' pour les "
"paramètres disponibles."

#: venv/lib/python3.10/site-packages/dj_rest_auth/jwt_auth.py:75
msgid "WIll override cookie."
msgstr "Remplacera le cookie."

#: venv/lib/python3.10/site-packages/dj_rest_auth/jwt_auth.py:86
msgid "No valid refresh token found."
msgstr "Aucun jeton d'actualisation valide n'a été trouvé."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:78
msgid "Define callback_url in view"
msgstr "Définissez “callback_url” dans la vue"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:87
msgid "View is not defined, pass it as a context variable"
msgstr "La “View” n’est pas définie, passez la en variable contextuelle"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:92
msgid "Define adapter_class in view"
msgstr "Définissez “adapter_class” dans la vue"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:118
msgid "Define client_class in view"
msgstr "Définissez “client_class” dans la vue"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:139
msgid "Failed to exchange code for access token"
msgstr "Échec de l'échange de code pour le jeton d'accès"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:150
msgid "Incorrect input. access_token or code is required."
msgstr "Paramètres incorrects. Il faut “access_token” ou “code”."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:163
msgid "Incorrect value"
msgstr "Paramètre incorrect"

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:180
#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:188
msgid "User is already registered with this e-mail address."
msgstr "Un utilisateur existe déjà avec cette adresse email."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:243
msgid "A user is already registered with this e-mail address."
msgstr "Un utilisateur existe déjà avec cette adresse email."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/serializers.py:252
msgid "The two password fields didn't match."
msgstr "Les deux mots de passes ne sont pas les mêmes."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py:52
msgid "Verification e-mail sent."
msgstr "Un email de vérification a été envoyé."

#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py:121
#: venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py:142
msgid "ok"
msgstr "ok"

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:33
msgid "Must include \"email\" and \"password\"."
msgstr "Doit inclure “email” et “password”."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:42
msgid "Must include \"username\" and \"password\"."
msgstr "Doit inclure “username” et “password”."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:53
msgid "Must include either \"username\" or \"email\" and \"password\"."
msgstr "Doit inclure un “username” ou “email”, et un “password”."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:99
#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:124
msgid "Unable to log in with provided credentials."
msgstr "Connexion impossible avec les informations fournies."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:106
msgid "User account is disabled."
msgstr "Le compte utilisateur est désactivé."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:115
msgid "E-mail is not verified."
msgstr "L’adresse email n’a pas été vérifiée."

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:287
#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:290
msgid "Invalid value"
msgstr "Valeur incorrect"

#: venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py:334
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr ""
"Votre ancien mot de passe a été mal saisi. Veuillez le saisir à nouveau."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:155
msgid "You should be logged in to logout. Check whether the token is passed."
msgstr ""

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:167
msgid "Successfully logged out."
msgstr "Déconnexion effectuée avec succès."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:191
#, fuzzy
#| msgid "Refresh token was not included in request data."
msgid "Refresh token was not included in cookie data."
msgstr ""
"Le jeton d'actualisation n'était pas inclus dans les données de la requête."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:197
msgid "Refresh token was not included in request data."
msgstr ""
"Le jeton d'actualisation n'était pas inclus dans les données de la requête."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:207
#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:211
msgid "An error has occurred."
msgstr "Une erreur est survenue."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:216
msgid ""
"Neither cookies or blacklist are enabled, so the token has not been deleted "
"server side. Please make sure the token is deleted client side."
msgstr ""
"Ni les cookies ni la liste noire ne sont activés, donc le jeton n'a pas été "
"supprimé côté serveur. Veuillez vous assurer que le jeton est supprimé côté "
"client."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:268
msgid "Password reset e-mail has been sent."
msgstr "L’email de réinitialisation du mot de passe a été envoyé."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:295
msgid "Password has been reset with the new password."
msgstr "Le mot de passe a été réinitialisé."

#: venv/lib/python3.10/site-packages/dj_rest_auth/views.py:318
msgid "New password has been saved."
msgstr "Le nouveau mot de passe est sauvé."

#~ msgid "Error"
#~ msgstr "Fehler"
